version: '3.8'

services:
  mysql:
    image: mysql:8
    container_name: mysql-urlshortener
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: url_shortener
    ports:
      - "3306:3306"
    restart: always

  redis:
    image: redis:latest
    container_name: redis-urlshortener
    ports:
      - "6379:6379"
    restart: always

  app:
    build: .
    container_name: urlshortener-app
    depends_on:
      - mysql
      - redis
    ports:
      - "8080:8080"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://mysql:3306/url_shortener
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=root
      - SPRING_REDIS_HOST=redis
